# WAP to display name, age , phone number and occupation of an user ( take user input)
name = input("Enter your name: ")
age = int(input("Enter your age: "))
pnum = int(input("Enter your phone number: "))
occu = input("Enter your occupation: ")
print('Your name is: ', name)
print('Your age is:' ,age)
print('Your phone number is: ',pnum)
print('Your occupation is: ', occu)